allprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'


    sourceCompatibility = JavaVersion.VERSION_11

    group = 'com.korwe'
    version = '4.0.0-SNAP{SHOT'

    repositories {
         mavenLocal()
         mavenCentral()
    }

    dependencies {
        testImplementation 'junit:junit:4.13.2'
    }

    test {
        ignoreFailures = true
    }
}
apply plugin: 'application'

mainClassName = 'com.korwe.thecore.service.CoreServices'

dependencies {
    runtimeOnly project(':api')
    runtimeOnly project(':router')
    runtimeOnly 'org.apache.logging.log4j:log4j-slf4j2-impl:2.23.1'
    runtimeOnly 'org.apache.logging.log4j:log4j-core:2.23.1'
}

distZip {
    archiveBaseName = 'thecore-javaservices'
}

