allprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'


    sourceCompatibility = JavaVersion.VERSION_11

    group = 'com.korwe'
    version = '2.1.0-b4'

    repositories {
         mavenLocal()
         mavenCentral()
    }

    dependencies {
        testImplementation 'junit:junit:4.13.2'
    }

    test {
        ignoreFailures = true
    }
}
apply plugin: 'application'

mainClassName = 'com.korwe.thecore.service.CoreServices'

dependencies {
    runtimeOnly project(':services')
    runtimeOnly project(':sessions')
    runtimeOnly project(':webcore')
    runtimeOnly project(':api')
    runtimeOnly project(':router')
    runtimeOnly 'org.postgresql:postgresql:42.5.0'
    runtimeOnly 'org.slf4j:slf4j-reload4j:2.0.2'
}

distZip {
    baseName = 'thecore-javaservices'
}

