ext {
    artifactory_contextUrl = project.properties['artifactory_contextUrl'] ?:
        'https://artifactory.paas.bayportfinance.com/artifactory'
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    sourceCompatibility = JavaVersion.VERSION_11

    group = 'com.korwe'
    version = (project.hasProperty('version') && project.version != 'unspecified') ? project.version : '4.1.0-SNAPSHOT'

    repositories {
        mavenLocal()
        maven {
            url "$artifactory_contextUrl/libs-release"
            mavenContent {
                releasesOnly()
            }
        }
        maven {
            url "$artifactory_contextUrl/libs-snapshot"
            mavenContent {
                snapshotsOnly()
            }
        }
        mavenCentral()
    }

    dependencies {
        testImplementation 'junit:junit:4.13.2'
    }

    test {
        ignoreFailures = true
    }
}
apply plugin: 'application'

mainClassName = 'com.korwe.thecore.service.CoreServices'

dependencies {
    runtimeOnly project(':api')
    runtimeOnly project(':router')
    runtimeOnly 'org.apache.logging.log4j:log4j-slf4j2-impl:2.23.1'
    runtimeOnly 'org.apache.logging.log4j:log4j-core:2.23.1'
}

distZip {
    archiveBaseName = 'thecore-javaservices'
}

