dependencies {
    implementation project(':api')
    implementation 'org.apache.camel:camel-core:3.18.1'
    implementation 'org.apache.camel:camel-rabbitmq:3.18.1'
    implementation 'org.apache.camel:camel-spring:3.18.1'
    implementation 'org.apache.camel:camel-spring-main:3.18.1'

}

apply plugin: 'application'

mainClassName = 'com.korwe.thecore.router.CamelRouter'

dependencies {
    runtimeOnly project(':api')
    runtimeOnly 'org.apache.logging.log4j:log4j-slf4j2-impl:2.23.1'
    runtimeOnly 'org.apache.logging.log4j:log4j-core:2.23.1'
}

distZip {
    archiveBaseName = 'thecore-router'
}

startScripts {
    classpath = files('src/dist/__CONF__') + classpath
    doLast {
        def windowsScriptFile = file getWindowsScript()
        def unixScriptFile    = file getUnixScript()
        windowsScriptFile.text = windowsScriptFile.text.replace('%APP_HOME%\\lib\\__CONF__', '%APP_HOME%\\conf')
        unixScriptFile.text  = unixScriptFile.text.replace('$APP_HOME/lib/__CONF__', '$APP_HOME/conf')
    }
}
